# Generated by Django 4.2.5 on 2023-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='Gnum',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
