# Generated by Django 4.2.5 on 2023-09-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_id_alter_students_gnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('CRN', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('courseID', models.CharField(max_length=6)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
    ]
