# Generated by Django 4.2.5 on 2023-09-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classes')),
            ],
        ),
    ]
