# Generated by Django 4.2.5 on 2023-09-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrolled',
            old_name='Gnum',
            new_name='student',
        ),
    ]
